In [4]:
import pandas as pd

In [5]:
# Load the dataset
DATA_PATH = "C:\\Users\\User\\Desktop\\PROJECT 2\\input\\CAR DETAILS FROM CAR DEKHO.csv"
df = pd.read_csv(DATA_PATH)

In [6]:
# ✅ Define reliable brands for low maintenance
RELIABLE_BRANDS = ["Maruti", "Toyota", "Hyundai"]

In [7]:
# Define luxury brands
LUXURY_BRANDS = ["Audi", "Mercedes", "BMW"]

In [8]:
# Function to recommend cars based on user input
def recommend_car(price, fuel_type, seller_type, owner_types, transmission_types, low_maintenance, luxury_preference):
    if not isinstance(owner_types, list):
        owner_types = [owner_types]  # Ensure owner_types is a list

    if not isinstance(transmission_types, list):
        transmission_types = [transmission_types]  # Ensure transmission_types is a list

    # Convert price to actual price range
    max_price = price * 100000 * 1.1  # Allow 10% buffer
    min_price = 50000  # Minimum price of ₹50,000

    # Filter cars based on price FIRST
    filtered_cars = df[
        (df['selling_price'].astype(float) <= max_price) & 
        (df['selling_price'].astype(float) >= min_price)
    ]

    # Apply remaining filters, including transmission type
    filtered_cars = filtered_cars[
        (filtered_cars['fuel'].str.strip().str.lower() == fuel_type.strip().lower()) &
        (filtered_cars['seller_type'].str.strip().str.lower() == seller_type.strip().lower()) &
        (filtered_cars['owner'].isin(owner_types)) &
        (filtered_cars['transmission'].isin(transmission_types))  # Filter based on transmission
    ]

    # Apply low maintenance filter if selected
    if low_maintenance.lower() == "yes":
        filtered_cars = filtered_cars[filtered_cars['name'].str.contains('|'.join(RELIABLE_BRANDS), case=False, na=False)]

    # Apply luxury car filter if selected
    if luxury_preference.lower() == "yes":
        filtered_cars = filtered_cars[filtered_cars['name'].str.contains('|'.join(LUXURY_BRANDS), case=False, na=False)]

    # Handle empty results
    if filtered_cars.empty:
        return pd.DataFrame({"message": ["❌ No matching cars found. Try different filters!"]})

    return filtered_cars.head(5)  # Return top 5 results

In [9]:
# Test the function with different scenarios
print("Beginner Driver Recommendations (Automatic only, Low Maintenance):")
display(recommend_car(10, "Petrol", "Dealer", ["First Owner"], ["Automatic"], "Yes", "No"))

print("\nExperienced Driver Recommendations (Automatic & Manual, All Brands):")
display(recommend_car(10, "Petrol", "Dealer", ["Second Owner", "Third Owner", "Fourth & Above Owner"], ["Automatic", "Manual"], "No", "No"))

print("\nLuxury Car Recommendations:")
display(recommend_car(50, "Petrol", "Dealer", ["First Owner", "Second Owner"], ["Automatic", "Manual"], "No", "Yes"))

Beginner Driver Recommendations (Automatic only, Low Maintenance):

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
558,Hyundai Grand i10 1.2 Kappa Magna AT,2017,550000,19890,Petrol,Dealer,Automatic,First Owner
561,Hyundai Grand i10 Magna AT,2017,520000,10510,Petrol,Dealer,Automatic,First Owner
577,Hyundai Grand i10 1.2 Kappa Magna AT,2017,550000,19890,Petrol,Dealer,Automatic,First Owner
580,Hyundai Grand i10 Magna AT,2017,520000,10510,Petrol,Dealer,Automatic,First Owner
596,Hyundai Grand i10 1.2 Kappa Magna AT,2017,550000,19890,Petrol,Dealer,Automatic,First Owner

Experienced Driver Recommendations (Automatic & Manual, All Brands):

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
65,Hyundai EON Magna Plus,2014,240000,73300,Petrol,Dealer,Manual,Second Owner
67,Maruti Alto LXi,2009,151000,66764,Petrol,Dealer,Manual,Second Owner
92,Hyundai Santro Xing XO,2007,80000,58000,Petrol,Dealer,Manual,Second Owner
97,Datsun RediGO 1.0 S,2017,210000,15000,Petrol,Dealer,Manual,Second Owner
434,Honda Brio E MT,2012,300000,85962,Petrol,Dealer,Manual,Second Owner

Luxury Car Recommendations:

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
41,Mercedes-Benz E-Class E 200 CGI Elegance,2010,850000,119000,Petrol,Dealer,Automatic,First Owner
101,Mercedes-Benz E-Class Exclusive E 200 BSIV,2018,4500000,9800,Petrol,Dealer,Automatic,First Owner
1081,Audi Q5 2.0 TFSI Quattro Premium Plus,2014,1850000,62237,Petrol,Dealer,Automatic,First Owner
2580,Mercedes-Benz E-Class Exclusive E 200 BSIV,2018,4500000,9800,Petrol,Dealer,Automatic,First Owner
3854,Audi Q5 2.0 TFSI Quattro Premium Plus,2014,1850000,62237,Petrol,Dealer,Automatic,First Owner